server:
  port: 8081
  
api:
  url: 
    domain: "jsonplaceholder.typicode.com"
    endpoint: "/users"

# spring:
#   datasource:
    #Postgres
    # driverClassName: "org.postgresql.Driver"
    # url: "jdbc:postgresql://localhost:5432/bc2405p_db"
    # username: "postgres"

    #MySQL
  #   driverClassName: "com.mysql.cj.jbdc.Driver"
  #   url: "jdbc:mysql://localhost:3306/bc2405p_db"
  #   username: "root"
  #   password: "Alabc123!"
  # jpa:
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       ddl-auto: create # update
  #       dialect: "org.hibernate.dialect.MySQL8Dialect"

spring:
  datasource:
    # Postgres
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/bc2405p_db"
    username: "postgres"
    password: "Alabc123!"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # update